Removed scrollbar and update to only show the prompt once the content has loaded
p-sam/electron-prompt pull request #83
Opened 2022-04-10 06:07 UTC by nfrance709

Updated, so the prompt is only shown once the contents have been rendered to prevent the user from seeing a brief blank window. See animated gifs below for before and after. Also updated overflow to hidden to remove to scroll bar.

Before
![before](https://user-images.githubusercontent.com/12604077/162604682-de1d5bb6-f5e1-42af-8719-a9e1e1125bf4.gif)

After
![after](https://user-images.githubusercontent.com/12604077/162604679-970a07cf-7aac-4d27-b82f-ab71a72d6908.gif)

2022-04-21 13:20 UTC, nfrance709 commented
Hi, Any plans to accept this pull request?

Do you require any changes to accept?

2022-04-21 17:22 UTC, p-sam commented
Hi, I didnt get time yet to have a proper look/test of this PR, but I have a few things to clarify:

- I would not want this change to make the prompt not appear at all, in cases where the prompt would fail to load part of the page assets (ex: in a future theorical case where Electron APIs evolves and break compat).
- To be honest, I'm fine with the "flashing" since it makes the prompt start to appear faster. Even if it's not yet fully rendered, the window at least appears relatively fast enough so you don't wonder what's going on yet.
- Shouldn't we fix the content to match the clientSize instead of hiding the scrollbars? It's just meant to be a generic same-y look across all platforms

2022-04-21 19:07 UTC, nfrance709 commented
Thank you for taking the time to respond, I'm sure you are probably busy with other things.

**_•	I would not want this change to make the prompt not appear at all, in cases where the prompt would fail to load part of the page assets (ex: in a future theorical case where Electron APIs evolves and break compat).
•	To be honest, I'm fine with the "flashing" since it makes the prompt start to appear faster. Even if it's not yet fully rendered, the window at least appears relatively fast enough so you don't wonder what's going on yet._**

The 'ready-to-show' event is widely used so I think its unlikely to cause compatible issues. I understand the point that the prompt does start to appear a little faster (although unusable) it doesn’t have a native feel (it feels like a webpage loading). Would you be open to accepting a pull request that allows the user to opt into only showing the prompt once the content is rendered if you prefer to keep the current behaviour?


The config option could be something like one of the following with a default value of false to retain the current behaviour, or perhaps you have a better suggestion for the option name?

showWhenReady
showWhenContentLoaded
waitUntilContentLoaded



**_•	Shouldn't we fix the content to match the clientSize instead of hiding the scrollbars? It's just meant to be a generic same-y look across all platforms_**

I checked and updating the DEFAULT_HEIGHT from 170 to 177 removes the scroll bar.

I also checked in Devtools and the following default user agent stylesheet is being applied:
body {
    display: block;
    margin: 8px;
    margin-top: 8px;
    margin-right: 8px;
    margin-bottom: 8px;
    margin-left: 8px;
}

Therefore, adding margin: 4px 8px; to the body in prompt.css also fixes the issue by reducing the top and bottom margins enough to so there is no overflow.


Also, I see you do have the customStylesheet which is nice, would you be open to allowing styles to be added without needing separate css file?

For example by add a new config option customStyles:

customStyles: '#container { overflow: hidden }'


For example a small change to prompt.js would allow adding css styles from file or from a string. There is no change to how the styles are applied.

```
function applyStyles(customStyleContent){
	const customStyle = document.createElement('style');
	customStyle.setAttribute('rel', 'stylesheet');
	customStyle.append(document.createTextNode(customStyleContent));
	document.head.append(customStyle);
}


try {
    if (promptOptions.customStylesheet) {
        const customStyleContent = fs.readFileSync(promptOptions.customStylesheet);
        if (customStyleContent) {
            applyStyles(customStyleContent);
        }
    }
} catch (error) {
    return promptError(error);
}


if (promptOptions.customStyles) {
    applyStyles(promptOptions.customStyles);
}
```


Also no offence taken if you don’t want to accept any pull requests and are happy with the how electron-prompt currently works. I can maintain a version with the modifications for my needs separately if needed.

2022-04-23 10:14 UTC, p-sam commented
I'm not against PRs at all, actually most of the last releases have been from PRs. I've been trying to keep the lib where it is, so fixes are more than welcome, but i'm trying to avoid adding new features or extending the scope of what electron-prompt does. You could say that custom stylesheets were out of scope already back when it was merged, I just had not realized it.

2022-04-23 17:22 UTC, nfrance709 commented
When you have time please take a look at the updated pull request. Its narrow in scope and doesn’t effect existing default behaviour:

1.	Removes the scroll bar that is appearing.
2.	Allow the user to opt into only showing the prompt when the content has rendered.


1.	Is a bug fix, the scroll bar is not supported to be there.
2.	Makes the prompt behave more like a native popup if the user wants it to, I understand you like the current behaviour and all existing users will retain that current behaviour.

2022-04-23 17:40 UTC, p-sam commented
You should either remove the showWhenReady option altogether, or document it, it's missing in the README

2022-04-23 18:06 UTC, nfrance709 commented
Ok, I've updated the README with the showWhenReady option

2022-04-23 18:15 UTC, p-sam requested changes
LGTM minus a minor nitpick on the README

2022-04-23 18:15 UTC, p-sam commented on README.md
> +| showWhenReady | (optional, boolean) Whether to only show the prompt window once its content has loaded to avoid an empty prompt from being displayed while the content is loading. Defaults to false.
Thanks for the wording, let's trim it so it's about the same length as the rest of the parameters description

```suggestion
| showWhenReady | (optional, boolean) Whether to only show the prompt window once content is loaded. Defaults to false. |
```

2022-04-23 18:20 UTC, p-sam approved these changes

2022-04-23 18:24 UTC, merged

2022-04-23 18:25 UTC, p-sam commented
Thank you for the PR and your time